### ISSUE TITLE
Conversation view -> Slide for details is buggy

### ISSUE THREAD

**Issue by fyahfox** [NemProject/NEMAndroidApp#170]
0.1.38
For some transactions it is hard to get them to slide, so you can see the fee and block. First I thought this only happens to transactions which have a longer message, but it happens to some 1 line TXes as well. I have to grab them at the very top, otherwise it won't work. This feels very clumsy/buggy. Please make it so you can grab the TX anywhere.

Also, why is it "display" or "not display"? It would be better if it really slides in, so people see that the slide has an effect from the very beginning. I almost made an issue "slide not implemented" until I found out it actually DOES work^^

**Comment by am4n0w4r** [comment]
Fixed in 0.1.39; Personally, I'd change swipe gesture to simple click, I think it is more intuitive

**Comment by fyahfox** [comment]
i talked it through with @jabo38 and i now understood that it was meant a bit different in the first place.

i think the general idea came from imessage (or some popular iOS app), and it should work like this:
swipe to left displays the details for ALL transaction in current conversation. it also shouldnt matter if you scroll up or down while swiping to the left, it will still display the details.

@jabo38 might comment in here to clarify or tell which iOS app is meant, so you can check that out. but the way it is right now, is really too clumsy.

**Comment by am4n0w4r** [comment]
I checked, currently this is implemented like in iOS version. I made some swipe detection improvements and added animations so it looks better, in 1.0.41;

**Comment by am4n0w4r** [comment]
Removed side movement effect impact on the list, in 1.0.41; The issue with direct reordering is that Android doesn't have standard reordering list control, so everything should be implemented manually. And with current implementation adding this effect can be tricky and time-consuming, because this is complex list and it will make the drag-n-drop workflow even more complex.

**Comment by am4n0w4r** [comment]
As there are no recent comments, I presume this is resolved

**Comment by fyahfox** [comment]
Besides that fact that this was ignored: "i think the general idea came from imessage (or some popular iOS app), and it should work like this:
swipe to left displays the details for ALL transaction in current conversation."

Now (1.0.48) I again have problems swiping a transation. It seems your earlier improvements (which definitely made it easier to swipe a TX) is not working any more.

**Comment by fyahfox** [comment]
Hello?

**Comment by am4n0w4r** [comment]
I investigated this issue more and found out that swipe is conflicting with message copying, the message label intercepts touch events so they don't pass to swipe detection mechanism. I think I can fix this but not 100% sure, and it will take some time to do that right. Do you agree with this solution? Please let me know so I can manage everything with @kmiliak

**Comment by am4n0w4r** [comment]
Fixed in 1.0.51;

**Comment by fyahfox** [comment]
well, i remember that we discussed the copy feature a lot and i think we decided to use the default android way (which is an editable selection and a copy button), but since i dont have a better idea how to solve this problem with this conflicting features, we should leave it as it is now.

thanks for the fix.
