### ISSUE TITLE
keyboard not closing at certain times

### ISSUE THREAD

**Issue by kodty** [NemProject/NEMAndroidApp#180]
phone make/model: sony xperia c1905
android version: 4.1.2
kernal: 3.4.0

when currently in the app, if you minimize it, open another app and then open the nem app again (to get the sign in page to come up), after signing in the key board remains open. if i click the back button at this time, while the key board is open, the back button, or minimize button as it shows at the time, acts as a back button causing the app to revert to the previous page instead of just closing the key board. this bug doesnt happen when the app is initially closed on the main page (where you select the account you wish to use). it only happens when on the "dashboard". 

this issue also affects the multisig set up page.

a side affect of this is that on the QR page in dash board, when the keyboard is open, if i select invoice or scan, the key board still remains open when it should close upon selection of another page.

**Comment by fyahfox** [comment]
@kodty 
We had a similar issue which was fixed, I think.
Please try with current version and report back.
