### ISSUE TITLE
duplicate names for accounts

### ISSUE THREAD

**Issue by kodty** [NemProject/NEMAndroidApp#183]
phone make/model: sony xperia c1905
android version: 4.1.2
kernal: 3.4.0

i can create any number of accounts with the same name, not sure how big of an issue this might be but it is probably a good idea if that isnt possible.

**Comment by fyahfox** [comment]
Hm, technically it's no problem, because the addresses are different of course.
Question is if we should prevent that from happening... Not sure really. If people want to do it, why not?
