### ISSUE TITLE
accounts can be deleted when the account has funds in it.

### ISSUE THREAD

**Issue by kodty** [NemProject/NEMAndroidApp#184]
phone make/model: sony xperia c1905
android version: 4.1.2
kernal: 3.4.0

this is quite dangerous. at minumum a warning message to say the account currently contains funds is needed, especially if two accounts can be named the same thing. 

edit: i didnt even notice the "undo" option that popped up. a pop up warning of some kind, or better yet,  have deletion of accounts be password protected, would be a huge improvement.

**Comment by jabo38** [comment]
Maybe if we make the message background in red?

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/14130906/7c99f57c-f671-11e5-92c6-13e3a821ff09.png)

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/14130912/89e643fc-f671-11e5-8599-460dd80e083e.png)

**Comment by jabo38** [comment]
It is pretty hard to miss that.

**Comment by kodty** [comment]
id say that would be much better and harder to miss.

**Comment by fyahfox** [comment]
I like both ideas.
Make the undo message more visible and also ask the user, if he really wants to delete an account, if it has funds init.
