### ISSUE TITLE
QR code scanning issue

### ISSUE THREAD

**Issue by kodty** [NemProject/NEMAndroidApp#185]
phone make/model: sony xperia c1905
android version: 4.1.2
kernal: 3.4.0

i think this could be an issue related to the phone being used, but its very difficult to get the app to pick up QR codes. with other QR code apps though, the QR codes get picked up quite easily and quickly.

issued is replicated on two of the same devices.

also the camera freezes sometimes while trying to scan a QR code.

**Comment by ninjalong** [comment]
phone make/model: samsung galaxy note 5 SM-N9208
android version: 5.1.1
kernal: 3.10.61-5943515

no issues so far with my note 5.

**Comment by fyahfox** [comment]
@kodty Please try again, there were some enhancements regarding scanning functionality.
