### ISSUE TITLE
not scanning QRs for accounts right

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMAndroidApp#191]
https://vid.me/AUBa

from Doraemon at https://forum.nem.io/t/nem-mobile-app-open-beta-and-10-000-xem-bug-bounty/1825/45?u=jabo38

**Comment by Dorawex** [comment]
here is the full detail of the android device 
**Model:**
nexus 7 2013
**Android **6.0.1
**kernel** 3.4.0-gd6b4cbf
nate@buildmachine-MS-7693 1
Thu Feb 18 02:42:26 EST 2016
**PureNexus Version**
6.01-20160218
**Build Number**
MMB29u
**BUild Date**
Thu Feb 18 02:39:26 EST 2016

**Comment by am4n0w4r** [comment]
Changed scanner engine to google's, seems to work better, in 1.0.47;

**Comment by fyahfox** [comment]
@Dorawex can you confirm this is fixed?

**Comment by jabo38** [comment]
tx hash:4e970dd76f6bbb382c4f4a56b7c0bd913141b0c5d969fe8b5d04b61d9d2485ab
bounty paid

**Comment by Dorawex** [comment]
sorry for my delay...
yes now it is working perfectly
good job
