### ISSUE TITLE
Deleting accounts: "Undo" feature buggy

### ISSUE THREAD

**Issue by fyahfox** [NemProject/NEMAndroidApp#197]
1.0.46

When I delete an account, the "undo" bar appears at the bottom.
1st problem: I can slide that bar to the side, which makes it impossible to undo a deletion as of then (no way to bring the bar back). Even worse: You can slide the bar by grabbing the actual "undo" button, I just did that without purpose and now the wrong account is gone and I can't undo.

2nd problem: When you slide the bar to the side, it doesn't only disappear for this screen, but it keeps beeing hidden after you click "Done" and "Edit" again.

My suggestion: Delete the "slide" feature for that bar completely.

**Comment by am4n0w4r** [comment]
It seems like common feature but surprisingly Android has no way to remove slide-to-remove feature on that control so this can be tricky.

**Comment by fyahfox** [comment]
Ok, what about a different control then?

**Comment by kmiliak** [comment]
Th solution here could be custom control which our developer can do, but it will require up to 2 days work.

**Comment by fyahfox** [comment]
Isn't there any other simple control that doesnt slide like this? This is really very bad UX and shouldn't stay like this imo.

**Comment by kmiliak** [comment]
We've found other solution:
When user swipes and hides the bar, developer can make in such way that this bar will come up back again.

**Comment by fyahfox** [comment]
hm ok, imo that is an ok tradeoff...

**Comment by am4n0w4r** [comment]
Fixed in 1.0.51;

**Comment by fyahfox** [comment]
ok, works good for me. thanks
