### ISSUE TITLE
2 languages appear in English.

### ISSUE THREAD

**Issue by appolloburning** [NemProject/NEMAndroidApp#205]
In language selection the bottom most language and the 3rd from bottom both appear in English.

**Comment by jabo38** [comment]
Yes, I know we don't have an Android translation for Korean right now.  Our translator got a lot of over time duty at her job, so had to take a break.  

I am not sure about the other language.

**Comment by fyahfox** [comment]
Please remove languages from list, which are not present yet.

**Comment by am4n0w4r** [comment]
Removed in 0.1.50;
