### ISSUE TITLE
App cannot return to itself when address sharing through gmail

### ISSUE THREAD

**Issue by martismartis** [NemProject/NEMAndroidApp#206]
tried to share my account address through gmail. As my gmail is not configured, I cannot return back to app from gmail. Closing gmail, starting app, it opens gmail. Only after reboot I could open an app.

Account id: NABDV6-53MBTO-JAP2EV-BS47JJ-3LFO7N-MNWSMC-ABDC
Android version: 1.0.48.b3179 BETA

**Comment by fyahfox** [comment]
after you click "share" and then chose email, what do you see? and is the back button not working in this situation?

**Comment by martismartis** [comment]
I used gmail. Back button working until first gmail screen and not until NEM app. Starting app again gives me first gmail screen, not the app. Had to reboot, to start NEM app from the beginning. Please note, that I don't have gmail account set, so I was in gmail account setting window, after clicked "share" and then "gmail".

**Comment by fyahfox** [comment]
Weird. When I try to reproduce it with another mail app, which is not configured on my phone, the back button works without problems.
Maybe the devs have an idea why this happens? Please try to reproduce it with gmail, too.

Generally: You probably don't have to restart the phone. Killing the app should be enough.

**Comment by am4n0w4r** [comment]
This is a strange bug and not reproducible. Sharing is done via standard system way so all buttons should work and we have no control over it after user presses "Share" button, so there's nothing to fix from our side. Maybe gmail doesn't allow back if not configured, it can be changed only by Google. @martismartis you can always restart app by removing it from recent, or force closing it. I don't see a NEM issue here.
