### ISSUE TITLE
Deleting accounts: "Undo" bar blocks accounts (scrolling issue)

### ISSUE THREAD

**Issue by fyahfox** [NemProject/NEMAndroidApp#210]
1.0.49

Have a lot of accounts -> goto account list -> Edit -> delete one -> now "undo" bar appears and blocks bottom account, scrolling down not possible.

**Comment by am4n0w4r** [comment]
If I got it right, it's a default android snackbar and you can always remove it from screen by swiping to the right or press Undo

**Comment by fyahfox** [comment]
So you are saying the scrolling could only be enabled by a hack?

**Comment by am4n0w4r** [comment]
This is not a hack imo, because usually if user deletes account, they rather do it intentionally and can easily remove that bar, or unintentionally and then they press undo.

Anyway, I've fixed it - now scroll is not blocked. In 1.0.51;

**Comment by fyahfox** [comment]
nice, thank you
