### ISSUE TITLE
XEM Balance: Except English the XEM balance doesn't display the correct unit characters. Inconsistency amongst langs

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#214]
XEM Balance: Except English the XEM balance doesn't display the correct unit characters i.e. instead of 2,000.50 XEM it displays 2.000,50. It seems this was fixed in the English version but not in the rest. It seems it's inconsistent through non-English languages.

Also see https://github.com/NewEconomyMovement/NEMiOSApp/issues/196

![photo_2016-04-10_16-06-04](https://cloud.githubusercontent.com/assets/17099341/16063172/1951bdfc-3298-11e6-8cce-3061dbb9a8e4.jpg)
![photo_2016-04-10_16-05-58](https://cloud.githubusercontent.com/assets/17099341/16063177/1f74bc34-3298-11e6-8065-2dc505061577.jpg)
![photo_2016-04-10_16-05-48](https://cloud.githubusercontent.com/assets/17099341/16063181/248860ae-3298-11e6-9bc0-df0c165fc93c.jpg)
![photo_2016-04-10_16-05-41](https://cloud.githubusercontent.com/assets/17099341/16063184/29415f4c-3298-11e6-88c0-158fb10e647f.jpg)
![photo_2016-04-10_16-05-35](https://cloud.githubusercontent.com/assets/17099341/16063188/2d72342e-3298-11e6-9a87-bbd8b64df841.jpg)

Nem address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by fiazk** [comment]
This inconsistency also appears when introducing XEM amounts i.e. in english you need to type 1.9 XEM in Spanish 1,9. I believe this happens across all languages

**Comment by fyahfox** [comment]
I am a bit shocked this is still not fixed. @am4n0w4r @kmiliak please comment.

**Comment by kmiliak** [comment]
@fyahfox Unfortunately we hadn't opportunities to work on Android version last week, we worked on IOS build. Android is going to release new build this week.

**Comment by am4n0w4r** [comment]
I remember we discussed this earlier but don't remember where, somewhere in keyboard issues. The point is - every language has it's own common separator people are used to, like "," and it can be confusing for them to have different separator. It is not something we randomly choose, the separators for every language is taken from locale settings. Technically this is not difficult to set "." for every language, so it's your choice.

**Comment by fyahfox** [comment]
Current Android localization file looks like this: http://pastebin.com/3XuUv3qW

Where can I set the decimal separator? Did I miss an update from you for the translation tables?

**Comment by am4n0w4r** [comment]
Decimal separators for every language are configured at Android, not application level. It's something that OS supply for applications. We can override this behavior but I don't see the point in it.

**Comment by fyahfox** [comment]
Both... In English it is 10,500.24 XEM and in German that would be 10.500,24 XEM.

If Android does that automatically, why is it wrong in the app?

**Comment by am4n0w4r** [comment]
You say in German it would be 10.500,24 XEM. Above there is a screenshot of German version that shows 12.595,9 XEM, so I don't understand what is wrong here? Also I made two screenshots with device language Deutsch and app lang Deutsch, and they look the same..
![screenshot_2016-07-26-12-55-17](https://cloud.githubusercontent.com/assets/7976963/17135536/ecc8a90a-5338-11e6-8735-23c1630ffe69.png)
![screenshot_2016-07-26-12-58-18](https://cloud.githubusercontent.com/assets/7976963/17135537/ecc978f8-5338-11e6-90cf-2503fa9578ca.png)

**Comment by jabo38** [comment]
looks like German and English were okay to me.  They are suppose to be opposite.

**Comment by fyahfox** [comment]
I'm so sorry, I didn't look closly at the screenshot.. It seems all correct for me.
