### ISSUE TITLE
Buggy top bar in tx window

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#215]
If the top green bar is dragged up it cannot be reversed. When you try to drag it down you just drag down the mobile quick settings/notification bar, please see pictures. 
![photo_2016-06-15_12-09-35](https://cloud.githubusercontent.com/assets/17099341/16076437/a084ef14-32f3-11e6-85b8-5838e9bb8623.jpg)
![photo_2016-06-15_12-09-38](https://cloud.githubusercontent.com/assets/17099341/16076442/a75fc8e0-32f3-11e6-82cd-8c2f55ff2d6e.jpg)
![photo_2016-06-15_12-26-08](https://cloud.githubusercontent.com/assets/17099341/16076610/5e9a8d6a-32f4-11e6-98ae-e2099ea49271.jpg)

NEM Address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W
Mobile: Samsung Galaxy S3
NEM version 1.0.49

**Comment by fyahfox** [comment]
Horrible. I didn't even know you can drag the green bar up. @am4n0w4r why is this?

**Comment by am4n0w4r** [comment]
Fixed in 0.1.50; Never even thought that it could be dragged...

**Comment by jabo38** [comment]
Bounty paid.  Tx hash: 20c01c3b94dce8997d45c8c6d39a4d1cc51a92d1d9b9a328a10c8ba48294a9e6
