### ISSUE TITLE
String "Fee" button missing translation 

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#218]
It seems this was missed, please see "Fee" in the image below. It should display "Tarifa"

![photo_2016-06-15_15-04-04](https://cloud.githubusercontent.com/assets/17099341/16080719/67d2c422-330a-11e6-85b2-0dfde7c89c94.jpg)

NEM Address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W
Mobile: Samsung Galaxy S3
NEM version 1.0.49

**Comment by fyahfox** [comment]
So it is definitely not a missing translation but there is no string for it?

**Comment by fiazk** [comment]
@fyahfox that's correct

**Comment by fiazk** [comment]
@fyahfox the string fee is there (line 194 and 215 loc. file) however, it seems these are other "fee" strings

**Comment by am4n0w4r** [comment]
Fixed, there was a hardcoded string in the code. Localization files updated too;

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 289095d2ab312262917287dec3bb9bc0be570015ad81436305f2bbdc0d7d9125
