### ISSUE TITLE
String "Amount: Balance xyz XEM" wrong colour

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#219]
Shouldn't the string "**Amount: Balance xyz XEM**" be coloured black instead of grey? please see image below
![photo_2016-06-15_15-06-13](https://cloud.githubusercontent.com/assets/17099341/16080851/051c299e-330b-11e6-81ff-0ffb7867d9e7.jpg)

NEM Address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W
Mobile: Samsung Galaxy S3
NEM version 1.0.49

**Comment by fyahfox** [comment]
absolutely, yes. @am4n0w4r please fix, should be quick ;)

**Comment by am4n0w4r** [comment]
Fixed in 1.0.50;

**Comment by jabo38** [comment]
Bounty paid. Tx hash: 56cf982497f3c85296e0e66a7b7996564fd93b9c08bff6176eeae2ae71126df0
