### ISSUE TITLE
New tx contacts look-up

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#221]
When entering the address you only have the option to either type it or paste it. It would be useful if you could also see your contacts or at least recent addresses when you click into "enter address"

NEM Address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by jabo38** [comment]
if you have saved the person's name in your address book, there will be an auto-suggestion box that comes up as you start to type their name.
