### ISSUE TITLE
App shouldn't pull in all personal contacts

### ISSUE THREAD

**Issue by zachamo** [NemProject/NEMAndroidApp#224]
The presumption that someone may have financial transactions with any of their phone's contacts is a bit of a leap.. 

Current mobile banking apps would never attempt to integrate one's contacts with banking activities - do you have your friends and families bank account numbers stored on your phone? If you had an online banking app that loaded all your contacts, wouldn't that feel invasive?

I love the notion of contacts, but it should not assume my full list is relevant to NEM. 

Ideally I should be able to add NEM contacts, and could add them FROM my address book or manually -- this way I choose who appears in the app and who does not.

Also - if there was any vulnerability in the app, you're potentially exposing my contacts.. The app pulled in a bunch of work contacts from my exchange server -- not cool.

**Comment by fyahfox** [comment]
Please discuss in here: https://github.com/NemProject/NEMAndroidApp/issues/21
