### ISSUE TITLE
Edit button in Contacts has no impact at contacts without NEM address

### ISSUE THREAD

**Issue by zachamo** [NemProject/NEMAndroidApp#225]
If I click the Edit button on the Contacts page, it shows a pencil beside all contacts. For accounts that do not have a corresponding NEM address, whenever I click a contact, it prompts me to edit regardless of whether I'm in edit mode or not. I get that edit mode allows you to edit contacts that have NEM addresses, but I think from a UX perspective, more consistency would be best.. Also -- why even permit contact entries that don't have a NEM address?

**Comment by fyahfox** [comment]
Good catch. That is a pretty serious bug @am4n0w4r. Phone contacts could be destroyed that way. Please fix. Non-NEM contacts should not be editable by the NEM app at all imo.

**Comment by am4n0w4r** [comment]
Fixed, now contacts can be editable only in edit mode.
Editing on non-NEM contacts is implemented intentionally in case user doesn't want to create new contact, just add address to existing. If this needs to be removed than, I guess, we can remove non-NEM contacts from address book view at all beacuse there is no point to show them.

**Comment by fyahfox** [comment]
Thx for the fix.

I'll leave this issue open, because I need to think about the other part.

**Comment by fyahfox** [comment]
Ok, so let's leave it as is for now.
