### ISSUE TITLE
Duplicated POI index symbol

### ISSUE THREAD

**Issue by MatCAlves** [NemProject/NEMAndroidApp#234]
It seems all other languages unless English are showing a duplicated POI index symbol. Just like "%ooo%ooo". At least at number zero of account importance.

Samsung Galaxy On7
Android 5.1.1
Kernel: 3.10.49
App version: 1.0.51.b3315

![screenshot_2016-07-30-18-44-19](https://cloud.githubusercontent.com/assets/20224023/17273337/92d19f36-5687-11e6-8647-2ae95348f25b.png)

**Comment by fyahfox** [comment]
confirmed for german language and non-zero poi score.

**Comment by am4n0w4r** [comment]
Fixed in 1.0.53;
