### ISSUE TITLE
Can not Exit the App from Login Screen via Back Button

### ISSUE THREAD

**Issue by mbush78** [NemProject/NEMAndroidApp#243]
Android N Beta 5 - Nexus 6
When on the Login Screen, Showing Enter Password Prompt

Expected Result: Backing out from Login Screen Exits and Terminates the App
Actual Result: Back Arrow just causes the screen to reload

TBYOK7-JXJLWU-AOQGOQ-43ZZGZ-TZDV4N-QG6XU4-QSDK

**Comment by fiazk** [comment]
I just tested it on .54 and this still happening

**Comment by am4n0w4r** [comment]
Should work in 1.0.60;

**Comment by jabo38** [comment]
@mbush78 you left a testnet account.  if you want a bounty you need to leave a mainnet account

**Comment by mbush78** [comment]
Thanks for pointing that out @jabo38 

NABGEW-YCDMLG-OSD2UI-G5OBA6-P2337Z-RODYY7-4LWB

**Comment by jabo38** [comment]
it seems like I have to press the back button twice.  Version 1.0.62

**Comment by am4n0w4r** [comment]
We need to press back button twice because first time always closes the soft keyboard.
What we can do:
1) not open keyboard when window is shown (easier),
2) intercept back button when keyboard is shown and close keyboard and window

**Comment by jabo38** [comment]
If I understand you correctly, option b) means when we hit the back button it will close the keyboard and window.  if that is the case, then that is the proper user experience.  nobody really wants the back button to close the soft keyboard, and everybody wants the keyboard up when landing on that screen.  There is really no reason to not have the keyboard up on that screen.  so it is best if the back button just minimizes the app.

**Comment by am4n0w4r** [comment]
Actually this is default system behavior: when soft keyboard is open, back button always closes it first. Yes, we can override this but just to note that this is more like a hack.

**Comment by jabo38** [comment]
yes, that makes sense.  I guess I understand why that is default.  

I would appreciate the "hack" though.  :-)  Thanks

**Comment by am4n0w4r** [comment]
Fixed;

**Comment by jabo38** [comment]
Bounty Paid Transaction Hash: 028f193a58d3fe03b6c739c337e0ead6bb824aab17e73af755232e8e9393599d
