### ISSUE TITLE
QR Scanner doesn't work

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMAndroidApp#245]
Tested with LG G3 and Galaxy S3.  Android 4.4.4.  At no point could I get QR scanner to work.

**Comment by am4n0w4r** [comment]
There was a small bug that was on some of Android 4+ devices. Should work in 1.0.60 versions.

**Comment by fiazk** [comment]
working on Android 4.3

**Comment by jabo38** [comment]
fixed
