### ISSUE TITLE
Cannot write to storage

### ISSUE THREAD

**Issue by meyns** [NemProject/NEMAndroidApp#247]
After trying to "Share QR" a message pops up saying "Cannot write to storage"
I'm on android 6.0.1 and using 1.0.60.b3373 BETA

**Comment by meyns** [comment]
In app-info in the NEM app in permissions there is only Camera and Contacts

**Comment by fiazk** [comment]
same for .6 mainnet

**Comment by am4n0w4r** [comment]
Fixed in testnet 1.0.62;

**Comment by jabo38** [comment]
fixed
