### ISSUE TITLE
Changing server, changes transfers and balances.

### ISSUE THREAD

**Issue by Kuppi74** [NemProject/NEMAndroidApp#249]
Hi, my account is somehow living doublelife, I have used two latest android testnet apk´s, now 1.061
Phone is Oneplus 3. (Account if bounty NDGL36-26SODK-ZZQ7NZ-YC6573-GS55SY-23LLIP-4GOQ)

with two server(37.120.188.83 & 188.68.50.161) its like this, different with [tembex](http://bob.nem.ninja:8765/#/account/TB4QWSWIZGA2RH6WNA5LCRXDM2LELWAH5IRL66NG/0)
![screenshot_20160905-102353](https://cloud.githubusercontent.com/assets/21452409/18240548/38971bdc-7355-11e6-9de1-ef51776f8e10.png)
here is transactions with Fiazk account
![screenshot_20160905-102400](https://cloud.githubusercontent.com/assets/21452409/18240561/4858610c-7355-11e6-9222-e3c7bb67012f.png)
then changing server
![screenshot_20160905-102412](https://cloud.githubusercontent.com/assets/21452409/18240574/4ff8fcbe-7355-11e6-8efa-d90e43c64159.png)
![screenshot_20160905-102420](https://cloud.githubusercontent.com/assets/21452409/18240583/58cd7b44-7355-11e6-95f1-5f373e203fa9.png)
now its same as in tembex (same with all other 3 servers)
![screenshot_20160905-102430](https://cloud.githubusercontent.com/assets/21452409/18240588/5f91318c-7355-11e6-8ebb-4e5fa9f784ac.png)
and that same Fiazk account again
![screenshot_20160905-102442](https://cloud.githubusercontent.com/assets/21452409/18240597/6883c0f2-7355-11e6-8e42-3d630a6a4ba8.png)
once it did shows both Fiazk transfers same time
![screenshot_20160901-093525](https://cloud.githubusercontent.com/assets/21452409/18240608/73074d3c-7355-11e6-8a30-aa8560a0c257.png)

**Comment by jabo38** [comment]
I'm just guessing this wasn't an app problem.  Recently the testnet forked. Some I'm just guessing some servers were up to date and some weren't.
