### ISSUE TITLE
Japanese localization

### ISSUE THREAD

**Issue by mizunashi** [NemProject/NEMAndroidApp#254]
Do you have the progress of the Japanese localization is made in any way?
And the Japanese version of the iPhone, but translation is different, looks like you are working separately.

If I can edit, I want to the Japanese localization.

https://github.com/NemProject/NEMAndroidApp/blob/e00f913afa2bd5dc5c33dcd83ffde496c89de3f9/app/src/main/res/values-ja/strings.xml

**Comment by jabo38** [comment]
@mizunashi, hi thank. I should have somebody working on improving the Japanese right now.  Thanks for the offer, I'll keep it in mind.
