### ISSUE TITLE
No warning dialog is shown when sharing QR on the exporting account

### ISSUE THREAD

**Issue by ponponpain** [NemProject/NEMAndroidApp#257]
No warning dialog is shown when sharing QR on the exporting account, while showing the secret key on the screen requires press the button of warning dialog.
As a result of no warning, it contains the secret key information, thus easily can export.

**Comment by am4n0w4r** [comment]
I'm not sure I understood correctly where is the issue

**Comment by ponponpain** [comment]
It's onShareClick() in ExportAccountActivity.java ConfirmDialogFragment is not shown.

https://github.com/NemProject/NEMAndroidApp/blob/master/app/src/main/java/org/nem/nac/ui/activities/ExportAccountActivity.java#L177

**Comment by am4n0w4r** [comment]
There is nothing to warn about on share - private key in QR code is encrypted and is not usable without decrypting using the right password
