### ISSUE TITLE
Design/Text issue with german language

### ISSUE THREAD

**Issue by cyrus1683** [NemProject/NEMAndroidApp#276]
**Android-version:** 7.1.1 (OnePlus 3T)
**app-version:** 1.0.66 BETA

**Issue:**
In the Account menu, on the top right, the "edit" button (in german bearbeiten) is to close to the right border. It looks really unprofessional. 
It needs a litle bit more space.

![screenshot_20170714-102905](https://user-images.githubusercontent.com/22840969/28205267-93b0368a-6881-11e7-8a5c-9d1592afc5e3.png)

NAQP6K-243JLR-GFVMJP-BX4VIQ-OHF5HA-YVVMHA-G5OU

**Comment by jabo38** [comment]
Bounty paid tx hash: d118db1e8bd7ff433462e30e1da335a3acc08793c80a8e8f9eca684dbfd56cdf
