### ISSUE TITLE
NEM client crashed while performing importance tx

### ISSUE THREAD

**Issue by tongokongo** [NemProject/NEMAndroidApp#277]
I tried to activate delegate account on my **multisignature** account. I performed the creation of "Multisignature importance transfer transaction" on my desktop (nanowallet) client on first cosignatory account. I tried to confirm it on my phone (second cosignatory account) but I was getting error about crash of the app. 

![image](https://user-images.githubusercontent.com/29152385/28691427-2f5e896a-731d-11e7-91f4-2abd036b0dea.png)
^ transaction waiting to be signed on nanowallet (issuer account)
![image](https://user-images.githubusercontent.com/29152385/28691487-6db8f682-731d-11e7-8410-d17876d2170e.png)
^trying to sign trasaction by phone, but after clicking "show" app is crashing with error "NEM client crashed, sending report..."
I am being send back to main screen:
![image](https://user-images.githubusercontent.com/29152385/28691568-c3992fc2-731d-11e7-8e3a-152bdaaa8747.png)

Rebooting doesn't help, error is replicable (everytime). I sent log files. Is there any route around this problem or should I import my phone account temporarly to nanowallet to approve this transaction?

I am using Xiaomi Redmi4a 1,4 GHz Quad Core, 2 GB RAM, Android 6.0.1.
NEM Mobile APP 1.0.66. BETA-Mainnet
Bounty if applicable:
NDZTPA-7AUVVD-AO2SXQ-77I3V4-ZSLETV-SPF7CT-RROE

**Comment by jabo38** [comment]
Bounty paid. tx hash: cee406d74366b3f90fc925ce13f79f05b81c73a2c066f479cf26cfb903524103
